### ISSUE TITLE
Breaks in a deno server 

### ISSUE THREAD

**Issue by nandorojo** [val-town/deno-http-worker#10]
Hey guys! Thanks for publishing this, I'm trying to figure out spinning up workers in deno. Currently I'm getting this error when I run this package from deno:

```tsx
[deno] error: TypeScript files are not supported in npm packages: file:///Users/.../Library/Caches/deno/npm/registry.npmjs.org/deno-http-worker/0.0.12/deno-bootstrap/index.ts
Error: Deno exited before being ready
    at ChildProcess.<anonymous> (file:///Users/.../Library/Caches/deno/npm/registry.npmjs.org/deno-http-worker/0.0.12/dist/DenoHTTPWorker.js:92:38)
    at ChildProcess.emit (ext:deno_node/_events.mjs:386:28)
    at ext:deno_node/internal/child_process.ts:154:16
    at eventLoopTick (ext:core/01_core.js:168:7) {
  stderr: undefined,
  stdout: undefined,
  code: 1,
  signal: null
}
```

# Reproduction

`deno run --allow-all index.ts`

The readme had some typos, but I fixed them here and tried to run the lib:

```tsx
// index.ts
import { newDenoHTTPWorker } from 'npm:deno-http-worker'

Deno.serve({ port: 8000 }, async (request) => {
  let worker = await newDenoHTTPWorker(
    `export default {
              async fetch(req: Request): Promise<Response> {
                  return Response.json({ ok: req.url });
              },
          }`,
    { printOutput: true, runFlags: ['--allow-net'] }
  )

  const body = await new Promise((resolve, reject) => {
    const req = worker.request(
      'https://hello/world?query=param',
      {},
      (resp) => {
        const body: any[] = []
        resp.on('error', reject)
        resp.on('data', (chunk) => {
          body.push(chunk)
        })
        resp.on('end', () => {
          resolve(Buffer.concat(body).toString())
        })
        console.log(resp)
      }
    )
    req.end()
  })
  console.log(body) // => {"ok":"https://hello/world?query=param"}

  worker.terminate()
  return new Response(body as string)
})
```

**Comment by nandorojo** [comment]
The solution was to use Node.js 19 instead of deno to run the starter example. 18 failed as it doesn't include `crypto`.
